### ISSUE TITLE
does the API expose ability to enable projects?

### ISSUE THREAD

**Issue by jonschlinkert** [pwmckenna/node-travis-ci#2]
I'd love to use your project to create a CLI for enabling travis for a GitHub project, but I can't find anything in the travis docs that mentions how that might be accomplished. Any advice? thanks!

**Comment by pwmckenna** [comment]
hi jon, off the top of my head, I believe that you'll want to use the sync call to make sure you have all the repos from github available, then toggle the active flag on the hook associated with the repo.

sync example is the third example down https://github.com/pwmckenna/node-travis-ci#users,

then you'll want to get all the hooks https://github.com/pwmckenna/node-travis-ci#hooks and update the one that you think is appropriate. good luck, and let me know if you run into any blockers. keep in mind that this won't save you from the web only oauth flow if the user doesn't have a travis account set up.

**Comment by jonschlinkert** [comment]
awesome, thanks for the feedback! great start. I'll let you know if I get it figured out

**Comment by jonschlinkert** [comment]
this is what I came up with: https://github.com/jonschlinkert/enable-travis. I haven't done a ton of CLI stuff, so any feedback is welcome about that or how the travis code was implemented. 

thanks again for your help!

**Comment by pwmckenna** [comment]
looks great! happy to help. I take it you ran into trouble with the sync bit?

**Comment by jonschlinkert** [comment]
thanks!

> I take it you ran into trouble with the sync bit?

technically I didn't do anything with it yet, I just wanted to get something basic working. I planned on trying to get that working today per your advice
