### ISSUE TITLE
Support Travis CI Enterprise

### ISSUE THREAD

**Issue by dlmr** [pwmckenna/node-travis-ci#21]
Hi!

I'm looking into using this project for communicating with a enterprise instance of Travis and it seems like there is no support for this currently. I'm wondering if a PR that adds this would be accepted and if there is any thoughts about how the API should look.

I have done some tests and it seems like this module works great as long as the endpoint is correct, as documented on [Travis CI](https://docs.travis-ci.com/api#overview).

Travis CI account | Endpoint
-- | --
open source projects on travis-ci.org | https://api.travis-ci.org
private projects on travis-ci.com | https://api.travis-ci.com
enterprise projects running on a custom domain | https://travis.example.com/api

My suggestion is to add an additional option to the constructor that takes a Travis CI Enterprise instance location; `enterprise`.
 
__Example__  
```js
var Travis = require('travis-ci');

// To access the Travis-CI Enterprise API
var travis = new Travis({
    version: '2.0.0',
    enterprise: 'https://travis.example.com'
});
```

**Comment by ljharb** [comment]
That seems reasonable, especially if your PR validates that the URL provided is valid.

**Comment by SimenB** [comment]
@ljharb what sort of validation do you want? Is `url.parse` and asserting that `protocol`, `host` and `path` is truthy enough?

**Comment by ljharb** [comment]
That’s probably a reasonable start
