### ISSUE TITLE
Replace request lib

### ISSUE THREAD

**Issue by cktang88** [pwmckenna/node-travis-ci#33]
Request is very bloated - https://bundlephobia.com/result?p=request@2.88.0

Can possibly replace with https://bundlephobia.com/result?p=node-fetch@2.6.0 or https://bundlephobia.com/result?p=axios@0.19.0 or something similar?

**Comment by ljharb** [comment]
Bundle phobia doesn’t apply to node-only libraries because they’re never bundled (and obsessing about package size is also often a waste of time)
